name: backend_app_tro
description: A server app using package:shelf.
version: 1.0.0

environment:
  sdk: ^3.0.0

dependencies:
  shelf: ^1.4.1
  shelf_router: ^1.1.4
  mysql_client: 0.0.27
  cloudinary: ^1.2.0
  dotenv: ^4.2.0
  http: ^1.6.0
  test: ^1.31.0
  shared_preferences: ^2.5.5

dev_dependencies:
  lints: ^3.0.0
